package com.example.appityappity.utils

const val TESTER_QUESTIONS = "tester_questions.json"
const val ANDROID_ANATOMY = "android_anatomy.json"
const val ANDROID_COMPONENTS = "android_components.json"
const val PROGRAMMING_PRINCIPLES = "programming_principles.json"
const val VIEW_AND_VIEWGROUP = "view_and_viewgroup.json"
const val TESTING = "testing.json"
const val THREADING = "threading.json"
const val KOTLIN_BASICS = "kotlin_basics.json"
const val COROUTINES = "coroutines.json"
const val DESIGN_PATTERNS = "design_patterns.json"
const val ANDROID_JETPACK = "android_jetpack.json"
const val CATEGORY_KEY = "ck"
const val TEST_SCORES = "test_scores"